### PR TITLE
✨ Prep for 015

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR updates the dependency on ks/kubeflex and the self-reference in Makefile, in preparation for the upcoming release (0.1.5).

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
/hold
@francostellari says we need a new Helm chart PR

**Comment by MikeSpreitzer** [comment]
The release process will publish the Helm chart.

/remove-hold

**Comment by MikeSpreitzer** [comment]
The force-push to 1d7aba8 is a rebase onto `main`.

**Review by nirrozenbaum — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
