### PR TITLE
✨ rename imbs to its

### PR DESCRIPTION
**Pull request by effi-ofer**
## Summary
Rename imbs to its.
This is part of issue #2024 (fixed by PR #2033) in the kubestellar repo.

## Related issue(s)

Fixes #

### CODE REVIEW

**Review by nirrozenbaum — APPROVED** [review]
/lgtm
/approve

**Comment by effi-ofer** [comment]
> @effi-ofer the commit is not signed..

What am I missing?  https://github.com/kubestellar/ocm-transport-plugin/pull/13/commits/327e2c07d69d3a92232cdff6d114be150fc20ba0
`Signed-off-by: Effi Ofer <effi.ofer@gmail.com>`

**Comment by nirrozenbaum** [comment]
I don't remember exactly but git needs to mark your commit as "verified", which in this case it doesn't do that

**Comment by nirrozenbaum** [comment]
image

this should appear next to your commits

**Comment by effi-ofer** [comment]
Done.  This repository requires gpg signing which is different from the ks requirements.  We should align the requirements for the two repos.

**Pull request merged**
