### PR TITLE
✨ Update version references for release 0.1.4

### PR DESCRIPTION
**Pull request by MikeSpreitzer**
## Summary
This PR updates the various version references in preparation for release 0.1.4.

## Related issue(s)

Fixes #

### CODE REVIEW

**Comment by MikeSpreitzer** [comment]
BTW, I do not understand why the `Makefile` says version 0.1.1 instead of 0.1.3.

**Review by nirrozenbaum — APPROVED** [review]
/lgtm
/approve

**Comment by nirrozenbaum** [comment]
@MikeSpreitzer the commit is not signed so merging is blocked..

**Comment by MikeSpreitzer** [comment]
@nirrozenbaum: thank you for the LGTM and approval. I do not understand what is going wrong wrt the signing. I signed and pushed this commit the same way I sign all my other commits:

```
mspreitz@mjs13 ocm-transport-plugin % git commit -a -s
[prep-for-0.1.4 3e0df23] Update self-references for release 0.1.4
 3 files changed, 88 insertions(+), 5 deletions(-)

mspreitz@mjs13 ocm-transport-plugin % git push -u origin prep-for-0.1.4
Enumerating objects: 9, done.
Counting objects: 100% (9/9), done.
Delta compression using up to 12 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 4.09 KiB | 4.09 MiB/s, done.
Total 5 (delta 4), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (4/4), completed with 4 local objects.
remote: 
remote: Create a pull request for 'prep-for-0.1.4' on GitHub by visiting:
remote:      https://github.com/MikeSpreitzer/kubestllar-ocm-transport-plugin/pull/new/prep-for-0.1.4
remote: 
To https://github.com/MikeSpreitzer/kubestllar-ocm-transport-plugin.git
 * [new branch]      prep-for-0.1.4 -> prep-for-0.1.4
branch 'prep-for-0.1.4' set up to track 'origin/prep-for-0.1.4'.
```

And Git seems to recognize that this commit is indeed signed by me:

Screenshot 2024-04-28 at 11 27 45 PM

**Comment by MikeSpreitzer** [comment]
There does seem to be something different between the commits in this repo vs those in ks/ks: the former are all marked "Verified" but the latter are not all marked "Verified".

Screenshot 2024-04-29 at 11 35 40 AM
Screenshot 2024-04-29 at 11 34 57 AM

**Pull request merged**
